module.exports = {
  oneHundred: '100m',
  fourHundred: '400m',
  k: '1K',
  mile: '1 mile',
  fiveK: '5K',
  tenK: '10K',
  tenMiles: '10 miles',
  halfMarathon: 'Half',
  twentyMiles: '20 miles',
  marathon: 'Marathon',
  pace: 'Pace',
  PROJECTED: 'Projected',
  SAME: 'Constant',
  PROJECTED_explanation: 'With proper training, these are the times you will get based on the highlighted time',
  SAME_explanation: 'If you ran at the highlighted pace at all distances, you would get the shown times',
};
